parameters:
  useWatchman: true

steps:

  - task: UseDotNet@2
    displayName: Use .NET Core SDK 3.0.100
    inputs:
      packageType: sdk
      version: 3.0.100

  - task: DownloadBuildArtifacts@0
    displayName: Download functional tests drop
    inputs:
      buildType: current
      downloadType: specific
      artifactName: FunctionalTests_$(platformFriendlyName)_$(configuration)
      downloadPath: $(Build.BinariesDirectory)

  - task: DownloadBuildArtifacts@0
    displayName: Download installers drop
    inputs:
      buildType: current
      downloadType: specific
      artifactName: Installers_$(platformFriendlyName)_$(configuration)
      downloadPath: $(Build.BinariesDirectory)

  - bash: |
      chmod +x $(Build.BinariesDirectory)/FunctionalTests_$(platformFriendlyName)_$(configuration)/src/Scripts/Mac/*.sh
      chmod +x $(Build.BinariesDirectory)/Installers_$(platformFriendlyName)_$(configuration)/*.sh
    displayName: Ensure all scripts are executable

  - ${{ if eq(parameters.useWatchman, 'true') }}:
    - bash: $(Build.BinariesDirectory)/Installers_$(platformFriendlyName)_$(configuration)/InstallScalar.sh
      displayName: Install product (with watchman)

  - ${{ if ne(parameters.useWatchman, 'true') }}:
    - bash: $(Build.BinariesDirectory)/Installers_$(platformFriendlyName)_$(configuration)/InstallScalar.sh --no-watchman
      displayName: Install product (without watchman)

  - bash: $(Build.BinariesDirectory)/FunctionalTests_$(platformFriendlyName)_$(configuration)/src/Scripts/Mac/RunFunctionalTests.sh $(configuration) --test-scalar-on-path --trace2-output=$(Build.ArtifactStagingDirectory)/logs/trace2-event.log
    displayName: Run functional tests

  - ${{ if eq(parameters.useWatchman, 'true') }}:
    - task: PublishTestResults@2
      displayName: Publish functional tests results
      inputs:
        testRunner: NUnit
        testResultsFiles: "**\\TestResult*.xml"
        searchFolder: $(System.DefaultWorkingDirectory)
        testRunTitle: macOS $(configuration) Functional Tests (with watchman)
        publishRunAttachments: true
      condition: succeededOrFailed()

  - ${{ if ne(parameters.useWatchman, 'true') }}:
    - task: PublishTestResults@2
      displayName: Publish functional tests results
      inputs:
        testRunner: NUnit
        testResultsFiles: "**\\TestResult*.xml"
        searchFolder: $(System.DefaultWorkingDirectory)
        testRunTitle: macOS $(configuration) Functional Tests (without watchman)
        publishRunAttachments: true
      condition: succeededOrFailed()
    
  - ${{ if eq(parameters.useWatchman, 'true') }}:
    - task: PublishBuildArtifacts@1
      displayName: Publish test and installation logs
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/logs'
        artifactName: Logs_$(platformFriendlyName)_Watchman
      condition: failed()

  - ${{ if ne(parameters.useWatchman, 'true') }}:
    - task: PublishBuildArtifacts@1
      displayName: Publish test and installation logs
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/logs'
        artifactName: Logs_$(platformFriendlyName)
      condition: failed()

  - bash: $(Build.BinariesDirectory)/FunctionalTests_$(platformFriendlyName)_$(configuration)/src/Scripts/Mac/CleanupFunctionalTests.sh
    displayName: Cleanup
    condition: always()

  - bash: sudo rm -rf $(Build.BinariesDirectory)/FunctionalTests_$(platformFriendlyName)_$(configuration)
    displayName: Cleanup phase 2
    condition: always()

