steps:

  - task: DownloadBuildArtifacts@0
    displayName: Download functional tests drop
    inputs:
      buildType: current
      downloadType: specific
      artifactName: FunctionalTests_$(platformFriendlyName)_$(configuration)
      downloadPath: $(Build.BinariesDirectory)

  - task: DownloadBuildArtifacts@0
    displayName: Download installers drop
    inputs:
      buildType: current
      downloadType: specific
      artifactName: Installers_$(platformFriendlyName)_$(configuration)
      downloadPath: $(Build.BinariesDirectory)

  - script: $(Build.BinariesDirectory)/Installers_$(platformFriendlyName)_$(configuration)\InstallScalar.bat $(Build.ArtifactStagingDirectory)\logs
    displayName: Install product

  - script: git config --global credential.interactive never
    displayName: Disable interactive auth

  - script: |
      SET PATH=C:\Program Files\Scalar;C:\Program Files\Git\cmd;%PATH%
      $(Build.BinariesDirectory)/FunctionalTests_$(platformFriendlyName)_$(configuration)/Scalar.FunctionalTests "--trace2-output=$(Build.ArtifactStagingDirectory)\logs\trace2-event.log"
    displayName: Run functional tests

  - task: PublishTestResults@2
    displayName: Publish functional tests results
    inputs:
      testRunner: NUnit
      testResultsFiles: "**\\TestResult*.xml"
      searchFolder: $(System.DefaultWorkingDirectory)
      testRunTitle: Windows $(configuration) Functional Tests
      publishRunAttachments: true
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: Publish test and installation logs
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)\logs'
      artifactName: Logs_$(platformFriendlyName)
    condition: failed()
